type: "transformation"
version: "1.0"
pipeline:
  components:
    Fixed Flow:
      type: "fixed-flow"
      parameters:
        componentName: "Fixed Flow"
        columns:
        - - "id"
          - "NUMBER"
          - ""
          - ""
        - - "name"
          - "VARCHAR"
          - ""
          - ""
        values:
        - - "1"
          - "A"
        - - "2"
          - "B"
        - - "3"
          - "C"
        - - "4"
          - "D"
design:
  components:
    Fixed Flow:
      position:
        x: 230
        "y": 140
      tempMetlId: 1
