type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "SQL Script"
      parameters:
        componentName: "Start"
    SQL Script:
      type: "sql-executor"
      parameters:
        componentName: "SQL Script"
        scriptLocation: "File"
        fileName: "Create_DB_SRC_DWH_tables.sql"
      postProcessing:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    SQL Script:
      position:
        x: 120
        "y": 0
      tempMetlId: 2
  notes:
    "1":
      position:
        x: 20
        "y": 90
      size:
        height: 78
        width: 300
      theme: "white"
      content: "Creating the src schema and dwh schema tables using SQL file"
